### ISSUE TITLE
코드 리팩토링

### ISSUE THREAD

**Issue by hhkim0729** [team-noir/the-pong#382]
- [x] 헤더 재사용성 높이기 (HeaderWithBackButton => Header)
- [x] api 리턴 타입 설정
- [x] 쿼리, 뮤테이션 위치
  - 페이지에 뿌려지는 데이터인 쿼리는 페이지에, 뮤테이션은 하위 컴포넌트에
- [x] 쿼리키 형식 통일: 명사로
- [x] page와 organism 분리
  - atomic 디자인 패턴을 나름 지켜보기 위함..
- [x] 스트링 리터럴을 const 변수로 변경
  - 서비스 이름, 쿼리키, 소켓 메시지, ....
- [x] 리스트의 결과가 없으면 없다고 표시
- [x] 개발용 푸터 삭제
- [x] 사용하지 않는 변수, import 삭제
- [x] 프로필 이미지 alt 통일

**Comment by hhkim0729** [comment]
🤔 템플릿의 에러바운더리와 서스펜스는 동작하지 않음..

**Comment by hhkim0729** [comment]
- 템플릿의 에러바운더리와 서스펜스가 기대와 같이 동작하지 않고 App의 것들을 사용
  🤔 삭제해야 하는 건가

**Comment by srngch** [comment]
- [ ] socket.on과 .emit 을 rest api 처럼 별도의 파일로 구분 `socket.v1.ts`
- [ ] 파일명 rename: `api.v1.ts` -> `rest.v1.ts`
