### ISSUE TITLE
게임 모드, 테마 구현

### ISSUE THREAD

**Issue by hhkim0729** [team-noir/the-pong#405]
## 구현할 내용

내용 상세 설명

## Tasks

- [ ] task

**Comment by srngch** [comment]
<img width="540" alt="image" src="https://user-images.githubusercontent.com/85778562/235351498-eea8ebf0-a71e-4475-92e6-e7513fa8bde7.png">

- '나' 플레이어 패들 컬러 코드: #CD392B
- 상대 플레이어 패들 컬러 코드: #C3BCBA

패들, 공에 적용될 쉐도우 css 값
```css
box-shadow: 0px 0px 21px 1px rgba(61, 54, 54, 0.25);
```
