### ISSUE TITLE
게임 시작 버튼을 눌렀을 때 나오는 게임 대기 상태 구현

### ISSUE THREAD

**Issue by srngch** [team-noir/the-pong#48]

**Comment by hhkim0729** [comment]
## 게임 시작하기
1. queue POST 요청
2. POST 성공 시
  a. ping pong 시작
  b. 게임 상대 대기 모달 노출 (취소 버튼)
  c. 소켓 queue 이벤트 리스닝 시작

## 대기 취소
1. queue DELETE 요청
2. DELETE 성공 시 대기 중 모달 숨김

## 매칭 실패
1. 60초가 지나서 타임아웃 queue 이벤트를 받음
2. 상대를 찾을 수 없음 모달 노출 (닫기 버튼)

## 매칭 성공
1. matched queue 이벤트를 받음
2. 이벤트 응답에 있는 gameId를 가지고 게임 설정 페이지로 이동
