### ISSUE TITLE
ExceptionsHandler 오류

### ISSUE THREAD

**Issue by srngch** [team-noir/the-pong#489]
## 구현할 내용

<img width="715" alt="image" src="https://user-images.githubusercontent.com/85778562/235858975-1ae2c244-2771-49db-a985-fb228a5fbe12.png">

**Comment by hhkim0729** [comment]
https://velog.io/@soshin_dev/ERRHTTPHEADERSSENT-Cannot-set-headers-after-they-are-sent-to-the-client-%EC%98%A4%EB%A5%98
