### ISSUE TITLE
날 차단한 회원에게 DM을 보내려고하면 응답으로 500에러

### ISSUE THREAD

**Issue by srngch** [team-noir/the-pong#534]
## 구현할 내용

```
the-pong_nginx     | 10.0.2.2 - - [07/May/2023:15:23:21 +0900] "GET /api/v1/dms/1 HTTP/1.1" 500 52 "http://localhost:8080/profile/1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/111.0" "-"
the-pong_backend   | [Nest] 1072  - 05/07/2023, 6:23:21 AM   ERROR [ExceptionsHandler] You cannot send dm to.
```

## Tasks

- [ ] task

**Comment by srngch** [comment]
DM 채널을 생성한 적이 없는 회원 간 차단
1. a가 b를 차단 -> 차단 해제 -> b가 a에게 메시지 보내기: 500에러
2. a가 b를 차단 -> 차단 해제 -> a가 b에게 메시지 보내기: DM 채널 생성됨
  - 채널은 생성되지만 실시간으로 톡을 주고 받을 수 없음
  - 새로고침하면 주고받은 톡이 뜸(즉, rest로는 잘 불러옴)

DM 채널을 생성한 적이 있는 회원 간 차단
- a가 b를 차단 -> 차단 해제: 채널 목록에 DM 채널 다시 잘 뜸. 하지만 위의 2번과 같은 문제 발생

**Comment by srngch** [comment]
DM 채널 생성해서 대화함 -> 차단 -> 차단 해제 -> 채널 목록에는 DM 채널이 잘 뜨지만, DM 채널 들어가서 소켓으로 대화가 오지 않음. rest로는 잘 와서 새로고침하면 뜹니다.

**Comment by srngch** [comment]
- 차단 당한 사람은
  - '메시지 보내기' 버튼 클릭(=DM 채널 생성) 가능
  - 채널 목록에서 날 차단한 사람의 DM 채널이 뜸
  - DM 채널 안에서 메시지 보내기 가능
- 차단한 사람은
  - '메시지 보내기' 버튼 클릭(=DM 채널 생성) 가능(그러나 의미없음)
  - 채널 목록에서 차단한 사람의 DM 채널이 뜨지 않음

**Comment by PCHANUL** [comment]
- 특정 유저를 차단하여 그 유저가 보내는 메세지와 dm을 보지 않는다.
- 소켓 메세지를 보낼때 자신을 블록한 사람인지 확인하고 보낸다.
- 블록을 해제할 때 ChannelUser에서도 제거한다.
