### ISSUE TITLE
문서 정리

### ISSUE THREAD

**Issue by srngch** [team-noir/the-pong#556]
### README
- [x] 기능 설명
- [x] 스택 추가
- [x] 팀원, 담당 업무 추가
- [ ] #570

**Comment by hhkim0729** [comment]
- [x] 노션 링크 추가
- [x] 한글 병기 → `README.md`는 한글로 작성하고 영어 문서를 `README-en.md` 파일을 별도로 작성
- [x] 목차 추가
- [x] 42 API 발급 설명 삭제 및 구글 로그인에 대한 설명 추가

----

- [ ] 기능 설명에 기술을 쓸 수 있다면 추가 (예: 소켓을 활용한 채팅 구현)
- [ ] 팀원 담당 업무 자세하게 설명
- [ ] 문제 해결 및 개발 로그 추가: 위키 작성 후 리드미에 링크 걸기

→ 이 내용들은 wiki에 글쓰고 README.md에 아래 커맨트처럼 제목과 링크만 추가

**Comment by srngch** [comment]
## 개발 로그 & 트러블슈팅

#### 2FA 로그인 플로우 구현 - @srngch [👉 자세히 보러가기](#)

- 문제 상황:
- 문제 해결:

#### 무한스크롤 - @hhkim0729 [👉 자세히 보러가기](#)

- 문제 상황:
- 문제 해결:

#### 게임 반응 속도를 올리기 위해 WebRTC - @PCHANUL [👉 자세히 보러가기](#)

- 문제 상황:
- 문제 해결:

#### 페이지네이션을 커서 방식으로 구현하기 - @PCHANUL [👉 자세히 보러가기](#)

- 문제 상황:
- 문제 해결:
