### ISSUE TITLE
메시지 리스트의 nextCursor값이 올바르지 않은 문제

### ISSUE THREAD

**Issue by hhkim0729** [team-noir/the-pong#568]
## 구현할 내용

메시지 리스트 요청 시 nextCursor 값이 현재 받은 리스트의 마지막 요소의 id 값을 가집니다.
다음 페이지 요청 시 같은 요소 하나를 중복으로 받게 되는 문제가 발생합니다.
<img width="403" alt="image" src="https://github.com/team-noir/the-pong/assets/72433681/df0b0370-5a65-4fce-962e-662e1b7b2968">

**Comment by PCHANUL** [comment]
#559 에서 해결되었습니다
